### ISSUE TITLE
Accessing vectors from a ROOT file

### ISSUE THREAD

**Issue by imoric** [scikit-hep/root_pandas#40]
Hi,

my ROOT file has second degree arrays. 
So every particle (currently row in DataFrame) has an array of values for different timeslices (currently array inside the row). Is it possible to access this information with root_pandas?
Now elements from the second degree arrays are all mixed together inside the row array.

Edit. so 1D array inside a 1D array

**Comment by mayou36** [comment]
Yes, you can. There are actually possible ways to do it, feel free to find your preferred one.

 - Use ROOT: you can transform your variable directly from ROOT. This means, instead of having a branch "B_PT" (which is an array), you specify "B_PT[0]" as the column to be used in root_pandas. Similar to writing "sqrt(B_PT)" etc. ATTENTION: by default, root_pandas tries to use it's own logic for expansion of expressions, so in order for the above to work, you have to add an "noexpand:" in front of it. So the expression would be "noexpand:B_PT[0]" instead of "B_PT" and you will have a single value instead of an array.

- use root_pandas: There is a "flatten" option in "read_root" where you specify, which takes a branch (array) as an argument and expands it to several branches (with a trailing 1, 2, 3... I think). This behavior is different to the initial one where "flatten" took only a boolean and flattened everything.

Disadvantage of both approaches: You do not keep your original name. But: pandas DataFrames have a method called `[rename](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.rename.html)`, which lets you very easy rename columns.

It suggest to go for the second one, as it is the "preferred" way to go, for sure.

**Comment by chrisburr** [comment]
This should now be supported in `v0.3.1`.

**Comment by lukepolson** [comment]
Hi @chrisburr . Is the inverse process possible? For example, if I have a DataFrame where some column consists of lists, is there an easy way to store this in a ROOT ntuple where each element is a vector or something?
